.PHONY: install-cli
install-cli:
	curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
	unzip awscliv2.zip
	sudo ./aws/install
	rm -rf aws awscliv2.zip

.PHONY: install-vault
install-vault:
	curl -L -O "https://github.com/99designs/aws-vault/releases/latest/download/aws-vault-linux-amd64"
	sudo install -o root -g root -m 0755 aws-vault-linux-amd64 /usr/local/bin/aws-vault
	rm -f aws-vault-linux-amd64
